[mcp_servers.notes]
command = "python"
args = [
  "C:\\Users\\ilya1\\Documents\\rd_projects\\ai-engineering-course\\lesson 16 - mcp-model-context-protocol\\homework\\server.py"
]

[mcp_servers.notes.env]
NOTES_DB_PATH = "C:\\Users\\ilya1\\Documents\\rd_projects\\ai-engineering-course\\lesson 16 - mcp-model-context-protocol\\homework\\data\\notes.json"
